import { getAuthenticatedSpotifyWebToken } from "../../../src/core/spotify-renderer-auth.ts";
const debugPort = Number(process.env.SOGGFY_INVESTIGATION_CDP ?? "9231");

type Job={label:string;fileId:string;formatEnum:number;url?:string};
const jobs:Job[]=[
 {label:"C",fileId:"ec055420020038cebab78e26c76d99a9b64bdab8",formatEnum:1},
 {label:"D",fileId:"b790049a22dbc2526f4736be9807ce0be90444f8",formatEnum:1},
];
function rv(b:Uint8Array,p:number):[bigint,number]{let v=0n,s=0n;for(;;){const x=b[p++];v|=BigInt(x&127)<<s;if(!(x&128))return[v,p];s+=7n}}
function urls(b:Uint8Array){let p=0,a:string[]=[];while(p<b.length){let t;[t,p]=rv(b,p);const f=Number(t>>3n),w=Number(t&7n);if(w===0){let _;[_,p]=rv(b,p)}else if(w===2){let n;[n,p]=rv(b,p);const x=b.subarray(p,p+Number(n));p+=Number(n);if(f===2)a.push(new TextDecoder().decode(x))}else throw Error("wire")}return a}
const auth=await getAuthenticatedSpotifyWebToken({debugPort});
for(const j of jobs){const r=await fetch(`https://spclient.wg.spotify.com/storage-resolve/v2/files/audio/interactive/${j.formatEnum}/${j.fileId}?product=0&partner=`,{headers:{Authorization:`Bearer ${auth.accessToken}`,Accept:"application/x-protobuf","App-Platform":"WebPlayer"}});if(!r.ok)throw Error(`${j.label} resolve HTTP ${r.status}`);j.url=urls(new Uint8Array(await r.arrayBuffer()))[0];if(!j.url)throw Error("no url")}

const ts:any[]=await(await fetch("http://127.0.0.1:" + debugPort + "/json/list")).json(),t=ts.find(x=>x.type==="page"&&x.webSocketDebuggerUrl)??ts.find(x=>x.webSocketDebuggerUrl),ws=new WebSocket(t.webSocketDebuggerUrl);
await new Promise<void>((r,j)=>{ws.onopen=()=>r();ws.onerror=()=>j(new Error("ws"))});let id=0;const p=new Map<number,(m:any)=>void>();ws.onmessage=e=>{const m=JSON.parse(String(e.data));if(m.id&&p.has(m.id)){p.get(m.id)!(m);p.delete(m.id)}};
async function ev(expression:string){const i=++id,q=new Promise<any>(r=>p.set(i,r));ws.send(JSON.stringify({id:i,method:"Runtime.evaluate",params:{expression,awaitPromise:true,returnByValue:true}}));const m=await q;if(m.result?.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description??m.result.exceptionDetails.text);return m.result?.result?.value}

const src=`(async()=>{
const JOBS=${JSON.stringify(jobs)};
const root=document.querySelector('[data-testid="root"]')||document.body?.firstElementChild,fk=Object.getOwnPropertyNames(root).find(k=>k.startsWith('__reactFiber$'));let f=root[fk];while(f?.return)f=f.return;const st=[f];let reg;while(st.length){const c=st.pop(),v=c?.memoizedProps?.value;if(v&&v._map instanceof Map){const ds=[...v._map.keys()].filter(k=>typeof k==='symbol').map(k=>k.description);if(ds.includes('EsperantoTransport')&&ds.includes('PlayerAPI')){reg=v;break}}if(c?.sibling)st.push(c.sibling);if(c?.child)st.push(c.child)}
const get=n=>{for(const k of reg._map.keys())if(typeof k==='symbol'&&k.description===n)return reg.resolve(k);throw Error(n)},tr=get('EsperantoTransport'),pl=get('PlayerAPI');
const ve=v=>{v=BigInt(v);const a=[];while(v>127n){a.push(Number(v&127n)|128);v>>=7n}a.push(Number(v));return a},fb=(n,b)=>[...ve((BigInt(n)<<3n)|2n),...ve(b.length),...b],fs=(n,s)=>fb(n,[...new TextEncoder().encode(s)]),fu=(n,v)=>[...ve(BigInt(n)<<3n),...ve(v)];
const pv=(b,p)=>{let v=0n,s=0n;for(;;){const x=b[p++];v|=BigInt(x&127)<<s;if(!(x&128))return[v,p];s+=7n}};
const parse=b=>{let p=0,o={position:0,totalSize:0,final:false,error:0,data:null,previouslyCached:0,fromNetwork:0,hadCacheError:false};while(p<b.length){let t;[t,p]=pv(b,p);const f=Number(t>>3n),w=Number(t&7n);if(w===0){let v;[v,p]=pv(b,p);if(f===1)o.position=Number(v);if(f===2)o.totalSize=Number(v);if(f===3)o.final=!!v;if(f===4)o.error=Number(v);if(f===6)o.previouslyCached=Number(v);if(f===7)o.fromNetwork=Number(v);if(f===8)o.hadCacheError=!!v}else if(w===2){let n;[n,p]=pv(b,p);const x=b.slice(p,p+Number(n));p+=Number(n);if(f===5)o.data=x}else throw Error('wire')}return o};
const single=(m,p)=>tr.callSingle({service:'spotify.download.esperanto.proto.Download',method:m,payload:new Uint8Array(p)});
const isCached=async url=>{const b=await single('IsFileFullyCached',fb(1,fs(1,url)));if(!b.length)return false;let p=0,t,v;[t,p]=pv(b,p);[v,p]=pv(b,p);return !!v};
const mk=async j=>{const b=await single('CreateProgressiveFileStreamer',fs(1,j.url));let p=0,t,sid;[t,p]=pv(b,p);[sid,p]=pv(b,p);return{j,sid,sm:fu(1,sid)}};
const size=async s=>await new Promise((resolve,reject)=>{const req=[...fb(1,s.sm),...fu(2,0),...fu(3,1)];let h=tr.call({service:'spotify.download.esperanto.proto.Download',method:'RequestData',payload:new Uint8Array(req)},true,b=>{const x=parse(b);if(x.final)resolve(x.totalSize)},reject);setTimeout(()=>{try{h.cancel()}catch{};reject(Error('size timeout'))},10000)});
const hash=async parts=>{const n=parts.reduce((a,x)=>a+x.length,0),all=new Uint8Array(n);let p=0;for(const x of parts){all.set(x,p);p+=x.length}return [...new Uint8Array(await crypto.subtle.digest('SHA-256',all))].map(x=>x.toString(16).padStart(2,'0')).join('')};
const before=pl.getState(),cachedBefore=Object.fromEntries(await Promise.all(JOBS.map(async j=>[j.label,await isCached(j.url)]))),ss=await Promise.all(JOBS.map(mk)),sizes=await Promise.all(ss.map(size)),epoch=performance.now();
let cancelResolve;const canceled=new Promise(r=>cancelResolve=r);const cevents=[];let cbytes=0,cHandle;
cHandle=tr.call({service:'spotify.download.esperanto.proto.Download',method:'RequestData',payload:new Uint8Array([...fb(1,ss[0].sm),...fu(2,0),...fu(3,sizes[0])])},true,b=>{const x=parse(b);cevents.push({atMs:performance.now()-epoch,data:x.data?.length||0,network:x.fromNetwork,cached:x.previouslyCached,final:x.final});cbytes+=x.data?.length||0;if(cbytes>=131072){try{cHandle.cancel()}catch{};single('DestroyFileStreamer',ss[0].sm).then(()=>cancelResolve({atMs:performance.now()-epoch,bytes:cbytes,destroyed:true}),e=>cancelResolve({atMs:performance.now()-epoch,bytes:cbytes,destroyError:String(e)}))}},e=>cancelResolve({atMs:performance.now()-epoch,bytes:cbytes,error:String(e)}));
const devents=[],dparts=[];const dDone=new Promise((resolve,reject)=>{let done=false;const h=tr.call({service:'spotify.download.esperanto.proto.Download',method:'RequestData',payload:new Uint8Array([...fb(1,ss[1].sm),...fu(2,0),...fu(3,sizes[1])])},true,b=>{const x=parse(b);devents.push({atMs:performance.now()-epoch,data:x.data?.length||0,network:x.fromNetwork,cached:x.previouslyCached,final:x.final});if(x.data)dparts.push(x.data);if(x.final&&!done){done=true;hash(dparts).then(v=>resolve({hash:v}),reject)}},e=>{if(!done){done=true;reject(e)}});setTimeout(()=>{if(!done){done=true;try{h.cancel()}catch{};reject(Error('D timeout'))}},30000)});
const [cancelInfo,dResult]=await Promise.all([canceled,dDone]);await single('DestroyFileStreamer',ss[1].sm);
const cachedAfter=Object.fromEntries(await Promise.all(JOBS.map(async j=>[j.label,await isCached(j.url)])));
const d2=await mk(JOBS[1]),parts2=[],events2=[];const d2hash=await new Promise((resolve,reject)=>{let done=false;const h=tr.call({service:'spotify.download.esperanto.proto.Download',method:'RequestData',payload:new Uint8Array([...fb(1,d2.sm),...fu(2,0),...fu(3,sizes[1])])},true,b=>{const x=parse(b);events2.push(x);if(x.data)parts2.push(x.data);if(x.final&&!done){done=true;hash(parts2).then(resolve,reject)}},e=>{if(!done){done=true;reject(e)}});setTimeout(()=>{if(!done){done=true;try{h.cancel()}catch{};reject(Error('D reread timeout'))}},15000)});await single('DestroyFileStreamer',d2.sm);
const after=pl.getState();
return JSON.stringify({cachedBefore,cachedAfter,sizes,cancel:cancelInfo,C:{events:cevents.length,bytes:cbytes,lastAtMs:cevents.at(-1)?.atMs,finalSeen:cevents.some(x=>x.final)},D:{events:devents.length,bytes:devents.reduce((a,x)=>a+x.data,0),network:devents.reduce((a,x)=>a+x.network,0),firstAtMs:devents[0]?.atMs,lastAtMs:devents.at(-1)?.atMs,finalSeen:devents.some(x=>x.final),hash:dResult.hash,cachedRereadHash:d2hash,hashMatch:dResult.hash===d2hash,rereadNetwork:events2.reduce((a,x)=>a+x.fromNetwork,0)},player:{before:{uri:before?.item?.uri,isPaused:before?.isPaused,position:before?.positionAsOfTimestamp},after:{uri:after?.item?.uri,isPaused:after?.isPaused,position:after?.positionAsOfTimestamp}}});
})()`;
console.log(await ev(src));ws.close();
