/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'Spotify'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _RuneEntry;
struct _RuneCharClass;
struct __CFString;
struct std::__1::basic_ostream<char>;
struct std::__1::basic_ostream<char>_vtbl;
struct std::__1::bad_weak_ptr;
struct std::exception_vtbl;
struct std::__1::future_error;
struct std::logic_error;
struct std::__1::error_category;
struct std::__1::error_category_vtbl;
struct std::__1::system_error;
struct std::runtime_error;
struct std::__1::basic_istream<char>;
struct std::__1::basic_istream<char>_vtbl;
struct std::__1::basic_ifstream<char>;
struct __sFILE;
struct std::__1::codecvt<char, char, mbstate_t>;
struct std::__1::__shared_count_vtbl;
struct std::__1::basic_ofstream<char>;
struct std::__1::basic_stringbuf<char>;
struct std::__1::basic_streambuf<char>;
struct std::__1::basic_streambuf<char>_vtbl;
struct std::__1::locale;
struct std::__1::__assoc_sub_state;
struct std::__1::basic_stringstream<char>;
struct std::__1::basic_istringstream<char>;
struct std::__1::basic_ostringstream<char>;
struct std::__1::num_get<char>;
struct std::__1::ios_base;
struct std::__1::ios_base_vtbl;
struct std::__1::ios_base::failure;
struct std::__1::basic_ios<char>;
struct std::length_error;
struct std::out_of_range;
struct std::invalid_argument;
struct std::bad_variant_access;
struct std::bad_optional_access;
struct Block_descriptor_1;
struct __objc2_class;
struct shared_state;
struct RecentlyPlayedItem;
struct NSScriptCommandDescription;
struct NSScriptObjectSpecifier;
struct NSScriptClassDescription;
struct NSArray;
struct NSDictionary;
struct NSAppleEventDescriptor;
struct NSMutableDictionary;
struct SPTSynchronizer;
struct BNCSettings;
struct BNCPersistence;
struct BNCSettingsProxy;
struct BranchMutableDictionary;
struct BranchLinkProperties;
struct BranchUniversalObject;
struct BranchContentMetadata;

/* 3 */
typedef __int64 int64_t;

/* 2 */
typedef int64_t CMTimeValue;

/* 5 */
typedef int int32_t;

/* 4 */
typedef int32_t CMTimeScale;

/* 8 */
typedef unsigned int u_int32_t;

/* 7 */
typedef u_int32_t uint32_t;

/* 6 */
typedef uint32_t CMTimeFlags;

/* 9 */
typedef int64_t CMTimeEpoch;

/* 1 */
#pragma pack(push, 4)
struct CMTime
{
  CMTimeValue value;
  CMTimeScale timescale;
  CMTimeFlags flags;
  CMTimeEpoch epoch;
};
#pragma pack(pop)

/* 13 */
typedef int __darwin_wchar_t;

/* 12 */
typedef __darwin_wchar_t __darwin_rune_t;

/* 11 */
typedef unsigned __int64 __darwin_size_t;

/* 14 */
typedef unsigned int __uint32_t;

/* 15 */
struct _RuneRange
{
  int __nranges;
  _RuneEntry *__ranges;
};

/* 10 */
struct _RuneLocale
{
  char __magic[8];
  char __encoding[32];
  __darwin_rune_t (__cdecl *__sgetrune)(const char *, __darwin_size_t, const char **);
  int (__cdecl *__sputrune)(__darwin_rune_t, char *, __darwin_size_t, char **);
  __darwin_rune_t __invalid_rune;
  __uint32_t __runetype[256];
  __darwin_rune_t __maplower[256];
  __darwin_rune_t __mapupper[256];
  _RuneRange __runetype_ext;
  _RuneRange __maplower_ext;
  _RuneRange __mapupper_ext;
  void *__variable;
  int __variable_len;
  int __ncharclasses;
  _RuneCharClass *__charclasses;
};

/* 16 */
struct _RuneEntry
{
  __darwin_rune_t __min;
  __darwin_rune_t __max;
  __darwin_rune_t __map;
  __uint32_t *__types;
};

/* 17 */
struct _RuneCharClass
{
  char __name[14];
  __uint32_t __mask;
};

/* 19 */
struct __cppobj dispatch_object_s
{
};

/* 18 */
struct __cppobj dispatch_queue_s : dispatch_object_s
{
};

/* 20 */
struct __cppobj dispatch_queue_attr_s : dispatch_object_s
{
};

/* 22 */
typedef __int64 CFIndex;

/* 25 */
struct __CFAllocator;

/* 24 */
typedef const struct __CFAllocator *CFAllocatorRef;

/* 23 */
typedef const void *(__cdecl *CFDictionaryRetainCallBack)(CFAllocatorRef, const void *);

/* 26 */
typedef void (__cdecl *CFDictionaryReleaseCallBack)(CFAllocatorRef, const void *);

/* 28 */
typedef const __CFString *CFStringRef;

/* 27 */
typedef CFStringRef (__cdecl *CFDictionaryCopyDescriptionCallBack)(const void *);

/* 31 */
typedef unsigned __int8 Boolean;

/* 30 */
typedef Boolean (__cdecl *CFDictionaryEqualCallBack)(const void *, const void *);

/* 33 */
typedef unsigned __int64 CFHashCode;

/* 32 */
typedef CFHashCode (__cdecl *CFDictionaryHashCallBack)(const void *);

/* 21 */
struct CFDictionaryKeyCallBacks
{
  CFIndex version;
  CFDictionaryRetainCallBack retain;
  CFDictionaryReleaseCallBack release;
  CFDictionaryCopyDescriptionCallBack copyDescription;
  CFDictionaryEqualCallBack equal;
  CFDictionaryHashCallBack hash;
};

/* 29 */
struct __CFString
{
  void *isa;
  __int64 info;
  char *data;
  __int64 length;
};

/* 34 */
struct CFDictionaryValueCallBacks
{
  CFIndex version;
  CFDictionaryRetainCallBack retain;
  CFDictionaryReleaseCallBack release;
  CFDictionaryCopyDescriptionCallBack copyDescription;
  CFDictionaryEqualCallBack equal;
};

/* 37 */
typedef double CGFloat;

/* 36 */
struct CGPoint
{
  CGFloat x;
  CGFloat y;
};

/* 38 */
struct CGSize
{
  CGFloat width;
  CGFloat height;
};

/* 35 */
struct CGRect
{
  CGPoint origin;
  CGSize size;
};

/* 39 */
typedef CGRect NSRect;

/* 40 */
typedef std::ostream std::ostream;

/* 41 */
struct __cppobj std::ostream
{
  std::ostream_vtbl *__vftable /*VFT*/;
};

/* 42 */
struct /*VFT*/ std::ostream_vtbl
{
  void (__cdecl *~basic_ostream)(std::ostream *__hidden this);
  void (__cdecl *~basic_ostream_0)(std::ostream *__hidden this);
};

/* 43 */
struct __cppobj std::nothrow_t
{
};

/* 44 */
struct std::bad_weak_ptr_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~bad_weak_ptr)(std::bad_weak_ptr *__hidden this);
  void (__cdecl *~bad_weak_ptr_0)(std::bad_weak_ptr *__hidden this);
  const char *(__cdecl *what)(const std::bad_weak_ptr *__hidden this);
};

/* 46 */
struct __cppobj std::exception
{
  std::exception_vtbl *__vftable /*VFT*/;
};

/* 45 */
struct __cppobj std::bad_weak_ptr : std::exception
{
};

/* 47 */
struct /*VFT*/ std::exception_vtbl
{
  void (__cdecl *~exception)(std::exception *__hidden this);
  void (__cdecl *~exception_0)(std::exception *__hidden this);
  const char *(__cdecl *what)(const std::exception *__hidden this);
};

/* 48 */
struct std::future_error_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~future_error)(std::future_error *__hidden this);
  void (__cdecl *~future_error_0)(std::future_error *__hidden this);
  const char *(__cdecl *what)(const std::logic_error *__hidden this);
};

/* 51 */
struct __cppobj std::__libcpp_refstring
{
  const char *__imp_;
};

/* 50 */
struct __cppobj std::logic_error : std::exception
{
  std::__libcpp_refstring __imp_;
};

/* 52 */
struct __cppobj std::error_code
{
  int __val_;
  const std::error_category *__cat_;
};

/* 49 */
struct __cppobj std::future_error : std::logic_error
{
  std::error_code __ec_;
};

/* 53 */
struct __cppobj std::error_category
{
  std::error_category_vtbl *__vftable /*VFT*/;
};

/* 55 */
struct __cppobj std::error_condition
{
  int __val_;
  const std::error_category *__cat_;
};

/* 66 */
typedef char *std::allocator<char>::pointer;

/* 65 */
typedef std::allocator<char>::pointer std::__pointer<char, std::allocator<char>, std::allocator<char>, true>::type;

/* 64 */
typedef std::__pointer<char, std::allocator<char>, std::allocator<char>, true>::type std::allocator_traits<std::allocator<char>>::pointer;

/* 63 */
typedef std::allocator_traits<std::allocator<char>>::pointer std::string::pointer;

/* 71 */
typedef __darwin_size_t size_t;

/* 70 */
typedef size_t std::allocator<char>::size_type;

/* 69 */
typedef std::allocator<char>::size_type std::__size_type<std::allocator<char>, long, true>::type;

/* 68 */
typedef std::__size_type<std::allocator<char>, long, true>::type std::allocator_traits<std::allocator<char>>::size_type;

/* 67 */
typedef std::allocator_traits<std::allocator<char>>::size_type std::string::size_type;

/* 62 */
struct std::string::__long
{
  std::string::pointer __data_;
  std::string::size_type __size_;
  unsigned __int64 __cap_ : 63;
  unsigned __int64 __is_long_ : 1;
};

/* 73 */
typedef char std::string::value_type;

/* 72 */
struct std::string::__short
{
  std::string::value_type __data_[23];
  unsigned __int8 __size_ : 7;
  unsigned __int8 __is_long_ : 1;
};

/* 74 */
struct std::string::__raw
{
  std::string::size_type __words[3];
};

/* 61 */
union std::string::__rep::$BBC8CF68AFD2118CFD95232F156F26A4
{
  std::string::__long __l;
  std::string::__short __s;
  std::string::__raw __r;
};

/* 60 */
struct std::string::__rep
{
  union
  {
    std::string::__long __l;
    std::string::__short __s;
    std::string::__raw __r;
  };
};

/* 59 */
struct __cppobj std::__compressed_pair_elem<std::string::__rep, 0, false>
{
  std::string::__rep __value_;
};

/* 77 */
struct __cppobj std::__non_trivial_if<true>
{
};

/* 76 */
struct __cppobj std::allocator<char> : std::__non_trivial_if<true>
{
};

/* 75 */
struct __cppobj std::__compressed_pair_elem<std::allocator<char>, 1, true> : std::allocator<char>
{
};

/* 58 */
struct __cppobj std::__compressed_pair<std::string::__rep> : std::__compressed_pair_elem<std::string::__rep, 0, false>, std::__compressed_pair_elem<std::allocator<char>, 1, true>
{
};

/* 57 */
struct __cppobj std::string
{
  std::__compressed_pair<std::string::__rep> __r_;
};

/* 56 */
typedef std::string std::string;

/* 54 */
struct /*VFT*/ std::error_category_vtbl
{
  void (__cdecl *~error_category)(std::error_category *__hidden this);
  void (__cdecl *~error_category_0)(std::error_category *__hidden this);
  const char *(__cdecl *name)(const std::error_category *__hidden this);
  std::error_condition (__cdecl *default_error_condition)(const std::error_category *__hidden this, int __ev);
  bool (__cdecl *equivalent)(const std::error_category *__hidden this, int __code, const std::error_condition *__condition);
  bool (__cdecl *equivalent_0)(const std::error_category *__hidden this, const std::error_code *__code, int __condition);
  std::string (__cdecl *message)(const std::error_category *__hidden this, int __ev);
};

/* 78 */
struct std::system_error_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~system_error)(std::system_error *__hidden this);
  void (__cdecl *~system_error_0)(std::system_error *__hidden this);
  const char *(__cdecl *what)(const std::runtime_error *__hidden this);
};

/* 80 */
struct __cppobj std::runtime_error : std::exception
{
  std::__libcpp_refstring __imp_;
};

/* 79 */
struct __cppobj std::system_error : std::runtime_error
{
  std::error_code __ec_;
};

/* 81 */
struct std::istream_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_istream)(std::istream *__hidden this);
  void (__cdecl *~basic_istream_0)(std::istream *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_istream_1)(std::istream *__hidden this);
  void (__cdecl *~basic_istream_2)(std::istream *__hidden this);
};

/* 85 */
typedef __int64 ptrdiff_t;

/* 84 */
typedef ptrdiff_t std::streamsize;

/* 82 */
struct __cppobj std::istream
{
  std::istream_vtbl *__vftable /*VFT*/;
  std::streamsize __gc_;
};

/* 83 */
struct /*VFT*/ std::istream_vtbl
{
  void (__cdecl *~basic_istream)(std::istream *__hidden this);
  void (__cdecl *~basic_istream_0)(std::istream *__hidden this);
};

/* 86 */
struct std::ostream_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_ostream)(std::ostream *__hidden this);
  void (__cdecl *~basic_ostream_0)(std::ostream *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_ostream_1)(std::ostream *__hidden this);
  void (__cdecl *~basic_ostream_2)(std::ostream *__hidden this);
};

/* 87 */
struct std::ifstream_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_ifstream)(std::ifstream *__hidden this);
  void (__cdecl *~basic_ifstream_0)(std::ifstream *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_ifstream_1)(std::ifstream *__hidden this);
  void (__cdecl *~basic_ifstream_2)(std::ifstream *__hidden this);
};

/* 90 */
typedef char std::filebuf::char_type;

/* 91 */
typedef __sFILE FILE;

/* 107 */
union __mbstate_t
{
  char __mbstate8[128];
  __int64 _mbstateL;
};

/* 106 */
typedef __mbstate_t __darwin_mbstate_t;

/* 105 */
typedef __darwin_mbstate_t mbstate_t;

/* 104 */
typedef mbstate_t std::char_traits<char>::state_type;

/* 103 */
typedef std::char_traits<char>::state_type std::filebuf::state_type;

/* 108 */
typedef unsigned int std::ios_base::openmode;

/* 89 */
struct __cppobj std::filebuf
{
  char *__extbuf_;
  const char *__extbufnext_;
  const char *__extbufend_;
  char __extbuf_min_[8];
  size_t __ebs_;
  std::filebuf::char_type *__intbuf_;
  size_t __ibs_;
  FILE *__file_;
  const std::codecvt<char, char, mbstate_t> *__cv_;
  std::filebuf::state_type __st_;
  std::filebuf::state_type __st_last_;
  std::ios_base::openmode __om_;
  std::ios_base::openmode __cm_;
  bool __owns_eb_;
  bool __owns_ib_;
  bool __always_noconv_;
};

/* 88 */
struct __cppobj std::ifstream
{
  std::filebuf __sb_;
};

/* 93 */
struct __sbuf
{
  unsigned __int8 *_base;
  int _size;
};

/* 96 */
typedef __int64 __int64_t;

/* 95 */
typedef __int64_t __darwin_off_t;

/* 94 */
typedef __darwin_off_t fpos_t;

/* 97 */
struct __sFILEX;

/* 92 */
struct __sFILE
{
  unsigned __int8 *_p;
  int _r;
  int _w;
  __int16 _flags;
  __int16 _file;
  __sbuf _bf;
  int _lbfsize;
  void *_cookie;
  int (__cdecl *_close)(void *);
  int (__cdecl *_read)(void *, char *, int);
  fpos_t (__cdecl *_seek)(void *, fpos_t, int);
  int (__cdecl *_write)(void *, const char *, int);
  __sbuf _ub;
  __sFILEX *_extra;
  int _ur;
  unsigned __int8 _ubuf[3];
  unsigned __int8 _nbuf[1];
  __sbuf _lb;
  int _blksize;
  fpos_t _offset;
};

/* 100 */
struct __cppobj std::__shared_count
{
  std::__shared_count_vtbl *__vftable /*VFT*/;
  __int64 __shared_owners_;
};

/* 99 */
struct __cppobj std::locale::facet : std::__shared_count
{
};

/* 102 */
struct __cppobj std::codecvt_base
{
};

/* 98 */
struct __cppobj std::codecvt<char, char, mbstate_t> : std::locale::facet, std::codecvt_base
{
};

/* 101 */
struct /*VFT*/ std::__shared_count_vtbl
{
  void (__cdecl *~__shared_count)(std::__shared_count *__hidden this);
  void (__cdecl *~__shared_count_0)(std::__shared_count *__hidden this);
  void (__cdecl *__on_zero_shared)(std::__shared_count *__hidden this);
};

/* 109 */
struct std::ofstream_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_ofstream)(std::ofstream *__hidden this);
  void (__cdecl *~basic_ofstream_0)(std::ofstream *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_ofstream_1)(std::ofstream *__hidden this);
  void (__cdecl *~basic_ofstream_2)(std::ofstream *__hidden this);
};

/* 110 */
struct __cppobj std::ofstream
{
  std::filebuf __sb_;
};

/* 119 */
typedef char std::streambuf::char_type;

/* 122 */
typedef __int64 std::streamoff;

/* 127 */
struct __cppobj std::fpos<__mbstate_t>
{
  __mbstate_t __st_;
  std::streamoff __off_;
};

/* 126 */
typedef std::fpos<__mbstate_t> std::streampos;

/* 125 */
typedef std::streampos std::char_traits<char>::pos_type;

/* 131 */
typedef std::char_traits<char>::pos_type std::stringbuf::pos_type;

/* 121 */
typedef std::streamoff std::char_traits<char>::off_type;

/* 130 */
typedef std::char_traits<char>::off_type std::stringbuf::off_type;

/* 123 */
enum std::ios_base::seekdir : unsigned __int32
{
  beg = 0x0,
  cur = 0x1,
  end = 0x2,
};

/* 129 */
typedef int std::char_traits<char>::int_type;

/* 132 */
typedef std::char_traits<char>::int_type std::stringbuf::int_type;

/* 128 */
typedef std::char_traits<char>::int_type std::streambuf::int_type;

/* 111 */
struct std::stringbuf_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_stringbuf)(std::stringbuf *__hidden this);
  void (__cdecl *~basic_stringbuf_0)(std::stringbuf *__hidden this);
  void (__cdecl *imbue)(std::streambuf *__hidden this, const std::locale *__loc);
  std::streambuf *(__cdecl *setbuf)(std::streambuf *__hidden this, std::streambuf::char_type *__s, std::streamsize __n);
  std::stringbuf::pos_type (__cdecl *seekoff)(std::stringbuf *__hidden this, std::stringbuf::off_type __off, std::ios_base::seekdir __way, std::ios_base::openmode __wch);
  std::stringbuf::pos_type (__cdecl *seekpos)(std::stringbuf *__hidden this, std::stringbuf::pos_type __sp, std::ios_base::openmode __wch);
  int (__cdecl *sync)(std::streambuf *__hidden this);
  std::streamsize (__cdecl *showmanyc)(std::streambuf *__hidden this);
  std::streamsize (__cdecl *xsgetn)(std::streambuf *__hidden this, std::streambuf::char_type *__s, std::streamsize __n);
  std::stringbuf::int_type (__cdecl *underflow)(std::stringbuf *__hidden this);
  std::streambuf::int_type (__cdecl *uflow)(std::streambuf *__hidden this);
  std::stringbuf::int_type (__cdecl *pbackfail)(std::stringbuf *__hidden this, std::stringbuf::int_type __c);
  std::streamsize (__cdecl *xsputn)(std::streambuf *__hidden this, const std::streambuf::char_type *__s, std::streamsize __n);
  std::stringbuf::int_type (__cdecl *overflow)(std::stringbuf *__hidden this, std::stringbuf::int_type __c);
};

/* 113 */
typedef std::string std::stringbuf::string_type;

/* 114 */
typedef char std::stringbuf::char_type;

/* 112 */
struct __cppobj std::stringbuf
{
  std::stringbuf::string_type __str_;
  std::stringbuf::char_type *__hm_;
  std::ios_base::openmode __mode_;
};

/* 118 */
struct std::locale::__imp;

/* 117 */
struct __cppobj std::locale
{
  std::locale::__imp *__locale_;
};

/* 115 */
struct __cppobj std::streambuf
{
  std::streambuf_vtbl *__vftable /*VFT*/;
  std::locale __loc_;
  std::streambuf::char_type *__binp_;
  std::streambuf::char_type *__ninp_;
  std::streambuf::char_type *__einp_;
  std::streambuf::char_type *__bout_;
  std::streambuf::char_type *__nout_;
  std::streambuf::char_type *__eout_;
};

/* 124 */
typedef std::char_traits<char>::pos_type std::streambuf::pos_type;

/* 120 */
typedef std::char_traits<char>::off_type std::streambuf::off_type;

/* 116 */
struct /*VFT*/ std::streambuf_vtbl
{
  void (__cdecl *~basic_streambuf)(std::streambuf *__hidden this);
  void (__cdecl *~basic_streambuf_0)(std::streambuf *__hidden this);
  void (__cdecl *imbue)(std::streambuf *__hidden this, const std::locale *__loc);
  std::streambuf *(__cdecl *setbuf)(std::streambuf *__hidden this, std::streambuf::char_type *__s, std::streamsize __n);
  std::streambuf::pos_type (__cdecl *seekoff)(std::streambuf *__hidden this, std::streambuf::off_type __off, std::ios_base::seekdir __way, std::ios_base::openmode __which);
  std::streambuf::pos_type (__cdecl *seekpos)(std::streambuf *__hidden this, std::streambuf::pos_type __sp, std::ios_base::openmode __which);
  int (__cdecl *sync)(std::streambuf *__hidden this);
  std::streamsize (__cdecl *showmanyc)(std::streambuf *__hidden this);
  std::streamsize (__cdecl *xsgetn)(std::streambuf *__hidden this, std::streambuf::char_type *__s, std::streamsize __n);
  std::streambuf::int_type (__cdecl *underflow)(std::streambuf *__hidden this);
  std::streambuf::int_type (__cdecl *uflow)(std::streambuf *__hidden this);
  std::streambuf::int_type (__cdecl *pbackfail)(std::streambuf *__hidden this, std::streambuf::int_type __c);
  std::streamsize (__cdecl *xsputn)(std::streambuf *__hidden this, const std::streambuf::char_type *__s, std::streamsize __n);
  std::streambuf::int_type (__cdecl *overflow)(std::streambuf *__hidden this, std::streambuf::int_type __c);
};

/* 133 */
struct std::__assoc_sub_state_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~__assoc_sub_state)(std::__assoc_sub_state *__hidden this);
  void (__cdecl *~__assoc_sub_state_0)(std::__assoc_sub_state *__hidden this);
  void (__cdecl *__on_zero_shared)(std::__assoc_sub_state *__hidden this);
  void (__cdecl *__execute)(std::__assoc_sub_state *__hidden this);
};

/* 135 */
struct __cppobj std::exception_ptr
{
  void *__ptr_;
};

/* 140 */
struct _opaque_pthread_mutex_t
{
  __int64 __sig;
  char __opaque[56];
};

/* 139 */
typedef _opaque_pthread_mutex_t __darwin_pthread_mutex_t;

/* 138 */
typedef __darwin_pthread_mutex_t pthread_mutex_t;

/* 137 */
typedef pthread_mutex_t std::__libcpp_mutex_t;

/* 136 */
struct __cppobj std::mutex
{
  std::__libcpp_mutex_t __m_;
};

/* 145 */
struct _opaque_pthread_cond_t
{
  __int64 __sig;
  char __opaque[40];
};

/* 144 */
typedef _opaque_pthread_cond_t __darwin_pthread_cond_t;

/* 143 */
typedef __darwin_pthread_cond_t pthread_cond_t;

/* 142 */
typedef pthread_cond_t std::__libcpp_condvar_t;

/* 141 */
struct __cppobj std::condition_variable
{
  std::__libcpp_condvar_t __cv_;
};

/* 134 */
struct __cppobj std::__assoc_sub_state : std::__shared_count
{
  std::exception_ptr __exception_;
  std::mutex __mut_;
  std::condition_variable __cv_;
  unsigned int __state_;
};

/* 146 */
struct std::basic_stringstream<char>_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_stringstream)(std::basic_stringstream<char> *__hidden this);
  void (__cdecl *~basic_stringstream_0)(std::basic_stringstream<char> *__hidden this);
  __int64 vbaseOffset_0;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_stringstream_1)(std::basic_stringstream<char> *__hidden this);
  void (__cdecl *~basic_stringstream_2)(std::basic_stringstream<char> *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_1;
  void *rtti_1;
  void (__cdecl *~basic_stringstream_3)(std::basic_stringstream<char> *__hidden this);
  void (__cdecl *~basic_stringstream_4)(std::basic_stringstream<char> *__hidden this);
};

/* 147 */
struct __cppobj std::basic_stringstream<char>
{
  std::stringbuf __sb_;
};

/* 148 */
struct std::istringstream_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_istringstream)(std::istringstream *__hidden this);
  void (__cdecl *~basic_istringstream_0)(std::istringstream *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_istringstream_1)(std::istringstream *__hidden this);
  void (__cdecl *~basic_istringstream_2)(std::istringstream *__hidden this);
};

/* 149 */
struct __cppobj std::istringstream
{
  std::stringbuf __sb_;
};

/* 150 */
struct std::ostringstream_vtbl_layout
{
  __int64 vbaseOffset;
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_ostringstream)(std::ostringstream *__hidden this);
  void (__cdecl *~basic_ostringstream_0)(std::ostringstream *__hidden this);
  __int64 vcallOffset;
  __int64 thisOffset_0;
  void *rtti_0;
  void (__cdecl *~basic_ostringstream_1)(std::ostringstream *__hidden this);
  void (__cdecl *~basic_ostringstream_2)(std::ostringstream *__hidden this);
};

/* 151 */
struct __cppobj std::ostringstream
{
  std::stringbuf __sb_;
};

/* 156 */
struct std::iterator<std::input_iterator_tag, char, long long, char *, char>
{
};

/* 157 */
typedef std::streambuf std::istreambuf_iterator<char>::streambuf_type;

/* 155 */
struct __cppobj std::istreambuf_iterator<char> : std::iterator<std::input_iterator_tag, char, long long, char *, char>
{
  std::istreambuf_iterator<char>::streambuf_type *__sbuf_;
};

/* 154 */
typedef std::istreambuf_iterator<char> std::num_get<char>::iter_type;

/* 161 */
typedef unsigned int std::ios_base::iostate;

/* 152 */
struct std::num_get<char>_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~num_get)(std::num_get<char> *__hidden this);
  void (__cdecl *~num_get_0)(std::num_get<char> *__hidden this);
  void (__cdecl *__on_zero_shared)(std::locale::facet *__hidden this);
  std::num_get<char>::iter_type (__cdecl *do_get)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, bool *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_0)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, __int64 *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_1)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, __int64 *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_2)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, unsigned __int16 *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_3)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, unsigned int *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_4)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, unsigned __int64 *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_5)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, unsigned __int64 *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_6)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, float *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_7)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, double *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_8)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, long double *__v);
  std::num_get<char>::iter_type (__cdecl *do_get_9)(const std::num_get<char> *__hidden this, std::num_get<char>::iter_type __b, std::num_get<char>::iter_type __e, std::ios_base *__iob, std::ios_base::iostate *__err, void **__v);
};

/* 153 */
struct __cppobj std::num_get<char>
{
};

/* 160 */
typedef unsigned int std::ios_base::fmtflags;

/* 163 */
enum std::ios_base::event : unsigned __int32
{
  erase_event = 0x0,
  imbue_event = 0x1,
  copyfmt_event = 0x2,
};

/* 162 */
typedef void (__cdecl *std::ios_base::event_callback)(std::ios_base::event, std::ios_base *, int);

/* 158 */
struct __cppobj std::ios_base
{
  std::ios_base_vtbl *__vftable /*VFT*/;
  std::ios_base::fmtflags __fmtflags_;
  std::streamsize __precision_;
  std::streamsize __width_;
  std::ios_base::iostate __rdstate_;
  std::ios_base::iostate __exceptions_;
  void *__rdbuf_;
  void *__loc_;
  std::ios_base::event_callback *__fn_;
  int *__index_;
  size_t __event_size_;
  size_t __event_cap_;
  __int64 *__iarray_;
  size_t __iarray_size_;
  size_t __iarray_cap_;
  void **__parray_;
  size_t __parray_size_;
  size_t __parray_cap_;
};

/* 159 */
struct /*VFT*/ std::ios_base_vtbl
{
  void (__cdecl *~ios_base)(std::ios_base *__hidden this);
  void (__cdecl *~ios_base_0)(std::ios_base *__hidden this);
};

/* 164 */
struct std::ios_base::failure_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~failure)(std::ios_base::failure *__hidden this);
  void (__cdecl *~failure_0)(std::ios_base::failure *__hidden this);
  const char *(__cdecl *what)(const std::runtime_error *__hidden this);
};

/* 165 */
struct __cppobj std::ios_base::failure : std::system_error
{
};

/* 166 */
struct std::ios_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~basic_ios)(std::ios *__hidden this);
  void (__cdecl *~basic_ios_0)(std::ios *__hidden this);
};

/* 168 */
typedef std::char_traits<char>::int_type std::ios::int_type;

/* 167 */
struct __cppobj std::ios
{
  std::ostream *__tie_;
  std::ios::int_type __fill_;
};

/* 169 */
struct std::length_error_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~length_error)(std::length_error *__hidden this);
  void (__cdecl *~length_error_0)(std::length_error *__hidden this);
  const char *(__cdecl *what)(const std::logic_error *__hidden this);
};

/* 170 */
struct __cppobj std::length_error : std::logic_error
{
};

/* 171 */
struct std::out_of_range_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~out_of_range)(std::out_of_range *__hidden this);
  void (__cdecl *~out_of_range_0)(std::out_of_range *__hidden this);
  const char *(__cdecl *what)(const std::logic_error *__hidden this);
};

/* 172 */
struct __cppobj std::out_of_range : std::logic_error
{
};

/* 173 */
struct std::invalid_argument_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~invalid_argument)(std::invalid_argument *__hidden this);
  void (__cdecl *~invalid_argument_0)(std::invalid_argument *__hidden this);
  const char *(__cdecl *what)(const std::logic_error *__hidden this);
};

/* 174 */
struct __cppobj std::invalid_argument : std::logic_error
{
};

/* 175 */
struct std::bad_variant_access_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~bad_variant_access)(std::bad_variant_access *__hidden this);
  void (__cdecl *~bad_variant_access_0)(std::bad_variant_access *__hidden this);
  const char *(__cdecl *what)(const std::bad_variant_access *__hidden this);
};

/* 176 */
struct __cppobj std::bad_variant_access : std::exception
{
};

/* 177 */
struct std::bad_optional_access_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__cdecl *~bad_optional_access)(std::bad_optional_access *__hidden this);
  void (__cdecl *~bad_optional_access_0)(std::bad_optional_access *__hidden this);
  const char *(__cdecl *what)(const std::bad_optional_access *__hidden this);
};

/* 178 */
struct __cppobj std::bad_optional_access : std::exception
{
};

/* 181 */
struct objc_method;

/* 180 */
typedef struct objc_method *Method;

/* 179 */
struct objc_cache
{
  unsigned int mask;
  unsigned int occupied;
  Method buckets[1];
};

/* 182 */
struct mach_header_64
{
  uint32_t magic;
  int32_t cputype;
  int32_t cpusubtype;
  uint32_t filetype;
  uint32_t ncmds;
  uint32_t sizeofcmds;
  uint32_t flags;
  uint32_t reserved;
};

/* 185 */
typedef unsigned __int64 u_int64_t;

/* 184 */
typedef u_int64_t uint64_t;

/* 183 */
struct segment_command_64
{
  uint32_t cmd;
  uint32_t cmdsize;
  char segname[16] __strlit(C,"UTF-8");
  uint64_t vmaddr;
  uint64_t vmsize;
  uint64_t fileoff;
  uint64_t filesize;
  int32_t maxprot;
  int32_t initprot;
  uint32_t nsects;
  uint32_t flags;
};

/* 186 */
struct section_64
{
  char sectname[16] __strlit(C,"UTF-8");
  char segname[16] __strlit(C,"UTF-8");
  uint64_t addr;
  uint64_t size;
  uint32_t offset;
  uint32_t align;
  uint32_t reloff;
  uint32_t nreloc;
  uint32_t flags;
  uint32_t reserved1;
  uint32_t reserved2;
  uint32_t reserved3;
};

/* 187 */
struct linkedit_data_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint32_t dataoff;
  uint32_t datasize;
};

/* 188 */
struct symtab_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint32_t symoff;
  uint32_t nsyms;
  uint32_t stroff;
  uint32_t strsize;
};

/* 189 */
struct dysymtab_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint32_t ilocalsym;
  uint32_t nlocalsym;
  uint32_t iextdefsym;
  uint32_t nextdefsym;
  uint32_t iundefsym;
  uint32_t nundefsym;
  uint32_t tocoff;
  uint32_t ntoc;
  uint32_t modtaboff;
  uint32_t nmodtab;
  uint32_t extrefsymoff;
  uint32_t nextrefsyms;
  uint32_t indirectsymoff;
  uint32_t nindirectsyms;
  uint32_t extreloff;
  uint32_t nextrel;
  uint32_t locreloff;
  uint32_t nlocrel;
};

/* 191 */
union lc_str
{
  uint32_t offset;
};

/* 190 */
struct dylinker_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  lc_str name;
};

/* 194 */
typedef unsigned __int8 u_int8_t;

/* 193 */
typedef u_int8_t uint8_t;

/* 192 */
struct uuid_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint8_t uuid[16];
};

/* 195 */
struct build_version_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint32_t platform;
  uint32_t minos;
  uint32_t sdk;
  uint32_t ntools;
};

/* 196 */
struct source_version_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint64_t version;
};

/* 197 */
struct entry_point_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  uint64_t entryoff;
  uint64_t stacksize;
};

/* 199 */
struct dylib
{
  lc_str name;
  uint32_t timestamp;
  uint32_t current_version;
  uint32_t compatibility_version;
};

/* 198 */
struct dylib_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  dylib dylib;
};

/* 200 */
struct rpath_command
{
  uint32_t cmd;
  uint32_t cmdsize;
  union lc_str path;
};

/* 201 */
typedef signed __int64 _Unwind_Sword;

/* 202 */
typedef unsigned __int64 _Unwind_Ptr;

/* 203 */
typedef unsigned __int64 _Unwind_Internal_Ptr;

/* 204 */
typedef unsigned __int64 _Unwind_Word;

/* 205 */
typedef int _Unwind_Action;

/* 206 */
typedef unsigned __int64 _Unwind_Exception_Class;

/* 207 */
enum $BDF88968CAE1EA74E42809B9AE857E7C
{
  _URC_NO_REASON = 0x0,
  _URC_FOREIGN_EXCEPTION_CAUGHT = 0x1,
  _URC_FATAL_PHASE2_ERROR = 0x2,
  _URC_FATAL_PHASE1_ERROR = 0x3,
  _URC_NORMAL_STOP = 0x4,
  _URC_END_OF_STACK = 0x5,
  _URC_HANDLER_FOUND = 0x6,
  _URC_INSTALL_CONTEXT = 0x7,
  _URC_CONTINUE_UNWIND = 0x8,
};

/* 208 */
typedef void (__fastcall *_Unwind_Exception_Cleanup_Fn)(_Unwind_Reason_Code, struct _Unwind_Exception *);

/* 209 */
typedef _Unwind_Reason_Code (__fastcall *_Unwind_Personality_Fn)(int, _Unwind_Action, _Unwind_Exception_Class, struct _Unwind_Exception *, struct _Unwind_Context *);

/* 210 */
typedef _Unwind_Reason_Code (__fastcall *_Unwind_Stop_Fn)(int, _Unwind_Action, _Unwind_Exception_Class, struct _Unwind_Exception *, struct _Unwind_Context *, void *);

/* 211 */
typedef _Unwind_Reason_Code (__fastcall *_Unwind_Trace_Fn)(struct _Unwind_Context *, void *);

/* 212 */
typedef _Unwind_Sword __guard;

/* 213 */
struct type_info;

/* 214 */
struct Block_layout
{
  void *isa;
  int32_t flags;
  int32_t reserved;
  void (*invoke)(void *, ...);
  Block_descriptor_1 *descriptor;
};

/* 216 */
typedef unsigned __int64 uintptr_t;

/* 215 */
struct Block_descriptor_1
{
  uintptr_t reserved;
  uintptr_t size;
};

/* 217 */
struct Block_descriptor_2
{
  void (__cdecl *copy)(void *, const void *);
  void (__cdecl *dispose)(const void *);
};

/* 218 */
struct Block_descriptor_3
{
  const char *signature;
  const char *layout;
};

/* 219 */
struct OS_nw_connection;

/* 220 */
struct __objc2_prop
{
  char *name;
  char *attr;
};

/* 221 */
struct __objc2_prop_list
{
  uint32_t entrysize;
  uint32_t count;
};

/* 223 */
typedef void (*IMP)(void);

/* 222 */
struct __objc2_meth
{
  char *name;
  char *types;
  IMP imp;
};

/* 224 */
struct __objc2_meth_list
{
  uint32_t entrysize;
  uint32_t count;
};

/* 225 */
struct __objc2_ivar
{
  int32_t *offs;
  char *name;
  char *type;
  uint32_t align;
  uint32_t size;
};

/* 226 */
struct __objc2_ivar_list
{
  uint32_t entrysize;
  uint32_t count;
};

/* 227 */
struct __objc2_prot_list
{
  uint64_t count;
};

/* 228 */
struct __objc2_prot
{
  void *isa;
  char *name;
  __objc2_prot_list *prots;
  __objc2_meth_list *inst_meths;
  __objc2_meth_list *class_meths;
  __objc2_meth_list *opt_inst_meths;
  __objc2_meth_list *opt_class_meths;
  __objc2_prop_list *inst_props;
  uint32_t cb;
  uint32_t flags;
};

/* 229 */
struct __objc2_class_ro
{
  uint32_t flags;
  uint32_t ivar_base_start;
  uint32_t ivar_base_size;
  uint32_t reserved;
  void *ivar_lyt;
  char *name;
  __objc2_meth_list *base_meths;
  __objc2_prot_list *base_prots;
  __objc2_ivar_list *ivars;
  void *weak_ivar_lyt;
  __objc2_prop_list *base_props;
};

/* 230 */
struct __objc2_category
{
  char *name;
  __objc2_class *_class;
  __objc2_meth_list *inst_meths;
  __objc2_meth_list *class_meths;
  __objc2_prot_list *prots;
  __objc2_prop_list *props;
};

/* 231 */
struct __objc2_class
{
  __objc2_class *isa;
  __objc2_class *superclass;
  void *cache;
  void *vtable;
  __objc2_class_ro *info;
};

/* 232 */
struct __objc2_class_rw
{
  uint32_t flags;
  uint32_t version;
  __objc2_class_ro *ro;
  __objc2_meth_list *methods;
  __objc2_prop_list *properties;
  __objc2_prot_list *protocols;
  __objc2_class *firstSubclass;
  __objc2_class *nextSiblingClass;
  char *demangledName;
};

/* 235 */
typedef unsigned __int16 u_int16_t;

/* 234 */
typedef u_int16_t uint16_t;

/* 233 */
struct __objc2_class_rw1
{
  uint32_t flags;
  uint16_t witness;
  uint16_t index;
  void *ro_or_rw_ext;
  __objc2_class *firstSubclass;
  __objc2_class *nextSiblingClass;
};

/* 236 */
struct __objc2_class_rw1_ext
{
  const __objc2_class_ro *ro;
  __objc2_meth_list *methods;
  __objc2_prop_list *properties;
  __objc2_prot_list *protocols;
  char *demangledName;
  uint32_t version;
};

/* 237 */
struct CacheMigrator
{
};

/* 238 */
struct __shared_weak_count
{
};

/* 239 */
struct shared_ptr<spotify::desktop::CacheMigrator>
{
  CacheMigrator *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 243 */
struct objc_class;

/* 242 */
typedef struct objc_class *Class;

/* 241 */
struct NSObject
{
  Class isa;
};

/* 240 */
struct SPTCacheMigrationHelper
{
  NSObject super;
  NSWindow *_window;
  NSProgressIndicator *_progressBar;
  NSTextField *_messageView;
  shared_ptr<spotify::desktop::CacheMigrator> _migrator;
};

/* 252 */
struct shared_ptr<spotify::signals::connection::shared_state>
{
  shared_state *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 253 */
struct scoped_connection
{
  shared_ptr<spotify::signals::connection::shared_state> _state;
};

/* 255 */
struct __compressed_pair<spotify::desktop::RecentlyPlayedItem *, std::allocator<spotify::desktop::RecentlyPlayedItem>>
{
  RecentlyPlayedItem *__value_;
};

/* 256 */
struct vector<spotify::desktop::RecentlyPlayedItem, std::allocator<spotify::desktop::RecentlyPlayedItem>>
{
  RecentlyPlayedItem *__begin_;
  RecentlyPlayedItem *__end_;
  __compressed_pair<spotify::desktop::RecentlyPlayedItem *, std::allocator<spotify::desktop::RecentlyPlayedItem>> __end_cap_;
};

/* 257 */
struct __short
{
  char __data_[23];
  unsigned __int8 __padding_[];
  __int32 __size_ : 7;
  __int32 __is_long_ : 1;
};

/* 258 */
struct __long
{
  char *__data_;
  unsigned __int64 __size_;
};

/* 263 */
union $9ADDC57B5BB5597EB8468FFDC668FB3C
{
  __short var0;
  __long var1;
};

/* 260 */
struct __rep
{
  $9ADDC57B5BB5597EB8468FFDC668FB3C var0;
};

/* 261 */
struct __compressed_pair<std::string::__rep, std::allocator<char>>
{
  __rep __value_;
  int var0;
  signed __int16 var1;
};

/* 262 */
struct basic_string<char, std::char_traits<char>, std::allocator<char>>
{
  __compressed_pair<std::string::__rep, std::allocator<char>> __r_;
  signed __int64 var0;
};

/* 244 */
struct SPTClientMenuHandler
{
  NSObject super;
  scoped_connection _onItemsChangedConnection;
  vector<spotify::desktop::RecentlyPlayedItem, std::allocator<spotify::desktop::RecentlyPlayedItem>> _recentlyPlayedItems;
  bool _isLoggedIn;
  bool _isHardwareAccelerationEnabled;
  bool _isCurrentRTLEmulationToggledOn;
  bool _needsReloadForAutoRTL;
  NSWindow *_applicationMainWindow;
  NSMenu *_hiddenKeyboardShortcutsMenu;
  NSMenuItem *_playPauseMenuItem;
  signed __int64 _currentPlatformEmulation;
  signed __int64 _currentRTLEmulation;
  basic_string<char, std::char_traits<char>, std::allocator<char>> _regularLanguage;
};

/* 251 */
struct shared_state
{
};

/* 254 */
struct RecentlyPlayedItem
{
};

/* 245 */
struct SystemConnectionFactory
{
};

/* 246 */
struct shared_ptr<spotify::http::SystemConnectionFactory>
{
  SystemConnectionFactory *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 247 */
struct SPTClientAppDelegate
{
  NSObject super;
  bool _appHasBeenCreated;
  bool _startupHelperWasRunningOnStartup;
  SPTClientMenuHandler *_clientMenuHandler;
  void *_playerDelegate;
  NSObject *_appNapActivity;
  NSUserActivity *_pendingUserActivity;
  shared_ptr<spotify::http::SystemConnectionFactory> _httpSystemConnectionFactory;
};

/* 250 */
struct NSResponder
{
  NSObject super;
};

/* 249 */
struct NSApplication
{
  NSResponder super;
};

/* 248 */
struct SPTClientApplication
{
  NSApplication super;
  bool _handlingSendEvent;
};

/* 259 */
union $1426DAE108CCE3B06C5086A396C8C738
{
  __short __s;
  __long __l;
};

/* 264 */
struct __raw
{
  unsigned __int64 var0[3];
};

/* 265 */
struct UserIntent
{
  basic_string<char, std::char_traits<char>, std::allocator<char>> var0;
};

/* 267 */
struct NSView
{
  NSResponder super;
};

/* 266 */
struct DraggableView
{
  NSView super;
};

/* 270 */
struct NSControl
{
  NSView super;
};

/* 269 */
struct NSImageView
{
  NSControl super;
};

/* 268 */
struct NonDraggableView
{
  NSImageView super;
};

/* 271 */
struct SPTMediaPlayerHelper
{
  NSObject super;
  bool _playingLocally;
  int _finalisedPlaybackPosition;
  NSMutableArray *_installedTargets;
  MPNowPlayingInfoCenter *_infoCenter;
  MPRemoteCommandCenter *_commandCenter;
  void *_coreHandler;
};

/* 272 */
struct TrackMetadata
{
};

/* 273 */
struct shared_ptr<const spotify::desktop::TrackMetadata>
{
  TrackMetadata *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 274 */
struct PlayerState
{
  bool var0;
  bool var1;
  bool var2;
  bool var3;
  bool var4;
  bool var5;
  bool var6;
  bool var7;
  bool var8;
  bool var9;
  bool var10;
  bool var11;
  bool var12;
  shared_ptr<const spotify::desktop::TrackMetadata> var13;
  int var14;
};

/* 275 */
struct SPTTouchbarHelper
{
  NSObject super;
  void *_browserClient;
  NSTouchBar *_currentTouchbar;
};

/* 283 */
typedef void *NSString;

/* 279 */
typedef void *id;

/* 278 */
struct SPTAppleScriptItem
{
  NSObject super;
  NSString *_key;
  id _parentItem;
};

/* 276 */
struct SPTAppleScriptTrack
{
  SPTAppleScriptItem super;
  shared_ptr<const spotify::desktop::TrackMetadata> _trackInfo;
};

/* 277 */
struct SPTAppleScriptObjectModel
{
  NSObject super;
};

/* 301 */
struct $95D0E058AA848B6F13BD0972117C13EA
{
  unsigned __int32 hasEvaluatedReceivers : 1;
  unsigned __int32 hasEvaluatedArguments : 1;
  unsigned __int32 RESERVED : 30;
};

/* 281 */
struct NSScriptCommand
{
  NSObject super;
  NSScriptCommandDescription *_commandDescription;
  id _directParameter;
  NSScriptObjectSpecifier *_receiversSpecifier;
  id _evaluatedReceivers;
  NSDictionary *_arguments;
  NSMutableDictionary *_evaluatedArguments;
  $95D0E058AA848B6F13BD0972117C13EA _flags;
  id _moreVars;
  void *_reserved;
};

/* 280 */
struct SPPlayPauseScriptCommand
{
  NSScriptCommand super;
};

/* 285 */
typedef unsigned int UInt32;

/* 284 */
typedef UInt32 FourCharCode;

/* 282 */
struct NSScriptCommandDescription
{
  NSObject super;
  NSString *_suiteName;
  NSString *_plistCommandName;
  FourCharCode _classAppleEventCode;
  FourCharCode _idAppleEventCode;
  NSString *_objcClassName;
  NSObject *_resultTypeNameOrDescription;
  FourCharCode _plistResultTypeAppleEventCode;
  id _moreVars;
};

/* 291 */
typedef bool BOOL;

/* 299 */
typedef __int64 NSInteger;

/* 286 */
struct NSScriptObjectSpecifier
{
  NSObject super;
  NSScriptObjectSpecifier *_container;
  NSScriptObjectSpecifier *_child;
  NSString *_key;
  NSScriptClassDescription *_containerClassDescription;
  BOOL _containerIsObjectBeingTested;
  BOOL _containerIsRangeContainerObject;
  char _padding[2];
  NSAppleEventDescriptor *_descriptor;
  NSInteger _error;
};

/* 290 */
struct NSDictionary
{
  NSObject super;
};

/* 300 */
struct NSMutableDictionary
{
  NSDictionary super;
};

/* 288 */
struct NSClassDescription
{
  NSObject super;
};

/* 287 */
struct NSScriptClassDescription
{
  NSClassDescription super;
  NSString *_suiteName;
  NSString *_objcClassName;
  FourCharCode _appleEventCode;
  NSObject *_superclassNameOrDescription;
  NSArray *_attributeDescriptions;
  NSArray *_toOneRelationshipDescriptions;
  NSArray *_toManyRelationshipDescriptions;
  NSDictionary *_commandMethodSelectorsByName;
  id _moreVars;
};

/* 295 */
typedef FourCharCode ResType;

/* 294 */
typedef ResType DescType;

/* 298 */
struct OpaqueAEDataStorageType;

/* 297 */
typedef struct OpaqueAEDataStorageType *AEDataStorageType;

/* 296 */
typedef AEDataStorageType *AEDataStorage;

/* 293 */
#pragma pack(push, 2)
struct AEDesc
{
  DescType descriptorType;
  AEDataStorage dataHandle;
};
#pragma pack(pop)

/* 292 */
struct NSAppleEventDescriptor
{
  NSObject super;
  AEDesc _desc;
  BOOL _hasValidDesc;
  char _padding[3];
};

/* 289 */
struct NSArray
{
  NSObject super;
};

/* 302 */
struct SPNextTrackScriptCommand
{
  NSScriptCommand super;
};

/* 303 */
struct SPPreviousTrackScriptCommand
{
  NSScriptCommand super;
};

/* 304 */
struct SPPauseScriptCommand
{
  NSScriptCommand super;
};

/* 305 */
struct SPPlayScriptCommand
{
  NSScriptCommand super;
};

/* 306 */
struct SPPlayTrackScriptCommand
{
  NSScriptCommand super;
};

/* 307 */
struct SPTBrowserClientMacObjCAnnex
{
  NSObject super;
  void *_browserClient;
  SPTMediaPlayerHelper *_mediaPlayerHelper;
  SPTTouchbarHelper *_touchbarHelper;
};

/* 308 */
struct SPTRelaunchUpgrader
{
  NSObject super;
};

/* 309 */
struct OS_dispatch_queue;

/* 310 */
struct MacOSBleAdvertiser
{
  NSObject super;
  bool _currentlyAdvertising;
  bool _pendingAdvertisementStart;
  void *_analytics;
  void *_onBleStateChangedSignal;
  NSString *_serviceName;
  CBUUID *_serviceUUID;
  OS_dispatch_queue *_ble_queue;
  CBPeripheralManager *_peripheral;
  CBMutableService *_service;
  NSMutableArray *_characteristics;
};

/* 311 */
struct duration<long long, std::ratio<1, 1000000000>>
{
  signed __int64 __rep_;
};

/* 312 */
struct time_point<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>>
{
  duration<long long, std::ratio<1, 1000000000>> __d_;
};

/* 313 */
struct InternalLoadMeasurementManager
{
};

/* 314 */
struct shared_ptr<spotify::desktop::InternalLoadMeasurementManager>
{
  InternalLoadMeasurementManager *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 315 */
struct shared_ptr<std::map<int, spotify::desktop::ProcessInfo>>
{
  void *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 316 */
struct RuntimeUsageInfo
{
};

/* 317 */
struct shared_ptr<spotify::desktop::RuntimeUsageInfo>
{
  RuntimeUsageInfo *__ptr_;
  __shared_weak_count *__cntrl_;
};

/* 318 */
struct SPTInternalSystemLoadMeasurerMacImpl
{
  NSObject super;
  bool _loadMeasurementEnabled;
  bool _deviceInfoLoggingEnabled;
  bool _shouldStopCPULoadMonitorThread;
  bool _isCurrentlyLoggingHighCPUUsage;
  duration<long long, std::ratio<1, 1000000000>> _currentMainThreadLatency;
  duration<long long, std::ratio<1, 1000000000>> _currentCoreThreadLatency;
  double _currentCPULoadForAllSpotifyProcesses;
  double _currentCPULoadEntireSystem;
  duration<long long, std::ratio<1, 1000000000>> _lastProcessInfoCollectionDeltaTime;
  id _callback;
  NSRunLoop *_cpuLoadMonitorRunLoop;
  NSThread *_cpuLoadMonitorThread;
  NSTimer *_check_cpu_load_timer;
  time_point<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>> _lastProcessInfoCollectionTime;
  unsigned __int64 _mainThreadLatencyMeasurerSequenceNumber;
  unsigned __int64 _coreThreadLatencyMeasurerSequenceNumber;
  unsigned __int64 _lastReportedMainThreadLatencyMeasurerSequenceNumber;
  unsigned __int64 _lastReportedCoreThreadLatencyMeasurerSequenceNumber;
  shared_ptr<spotify::desktop::InternalLoadMeasurementManager> _manager;
  shared_ptr<std::map<int, spotify::desktop::ProcessInfo>> _previousProcessInfosSample;
  shared_ptr<std::map<int, spotify::desktop::ProcessInfo>> _currentProcessInfosSample;
  shared_ptr<spotify::desktop::RuntimeUsageInfo> _previousRuntimeUsageInfo;
  shared_ptr<spotify::desktop::RuntimeUsageInfo> _currentRuntimeUsageInfo;
};

/* 319 */
struct FingerprintExtractor
{
  NSObject super;
};

/* 320 */
struct SpotLightSearchHandler
{
  NSObject super;
  CSSearchableIndex *_searchableIndex;
};

/* 321 */
struct SearchContent
{
};

/* 322 */
struct __compressed_pair<spotify::desktop::search_handler::SearchContent *, std::allocator<spotify::desktop::search_handler::SearchContent>>
{
  SearchContent *var0;
};

/* 323 */
struct vector<spotify::desktop::search_handler::SearchContent, std::allocator<spotify::desktop::search_handler::SearchContent>>
{
  SearchContent *var0;
  SearchContent *var1;
  __compressed_pair<spotify::desktop::search_handler::SearchContent *, std::allocator<spotify::desktop::search_handler::SearchContent>> var2;
};

/* 324 */
struct SPTDefaultAVFoundationFactory
{
  NSObject super;
};

/* 325 */
struct SPTAVFoundationRendererObserver
{
  NSObject super;
  id _statusChangeHandler;
  AVSampleBufferAudioRenderer *_audioRenderer;
};

/* 326 */
struct SPTPlaybackAudioSessionWrapper
{
  NSObject super;
  NSNotificationCenter *_notificationCenter;
  NSObject *_mediaServicesWereResetNotificationHandle;
  id _onMediaServicesResetNotification;
  NSObject *_automaticFlushNotificationHandle;
  id _onAutomaticFlushNotification;
};

/* 327 */
struct MediaPlayer
{
};

/* 328 */
struct __compressed_pair<spotify::media_player::MediaPlayer *, std::default_delete<spotify::media_player::MediaPlayer>>
{
  MediaPlayer *__value_;
};

/* 329 */
struct unique_ptr<spotify::media_player::MediaPlayer, std::default_delete<spotify::media_player::MediaPlayer>>
{
  __compressed_pair<spotify::media_player::MediaPlayer *, std::default_delete<spotify::media_player::MediaPlayer>> __ptr_;
};

/* 330 */
struct SPTMediaPlayer
{
  NSObject super;
  unique_ptr<spotify::media_player::MediaPlayer, std::default_delete<spotify::media_player::MediaPlayer>> _media_player;
};

/* 331 */
struct Timeline
{
  void **var0;
};

/* 332 */
struct __compressed_pair<spotify::media_player::Timeline *, std::default_delete<spotify::media_player::Timeline>>
{
  Timeline *__value_;
};

/* 333 */
struct unique_ptr<spotify::media_player::Timeline, std::default_delete<spotify::media_player::Timeline>>
{
  __compressed_pair<spotify::media_player::Timeline *, std::default_delete<spotify::media_player::Timeline>> __ptr_;
};

/* 334 */
struct SPTTimeline
{
  NSObject super;
  unique_ptr<spotify::media_player::Timeline, std::default_delete<spotify::media_player::Timeline>> _timeline;
};

/* 335 */
struct SPTVideoRenderer;

/* 336 */
struct SPTVideo
{
  NSObject super;
  AVAsset *_asset;
  SPTVideoRenderer *_renderer;
};

/* 337 */
struct ObjCVideo
{
};

/* 338 */
struct __compressed_pair<spotify::media_player::ObjCVideo *, std::default_delete<spotify::media_player::ObjCVideo>>
{
  ObjCVideo *var0;
};

/* 339 */
struct unique_ptr<spotify::media_player::ObjCVideo, std::default_delete<spotify::media_player::ObjCVideo>>
{
  __compressed_pair<spotify::media_player::ObjCVideo *, std::default_delete<spotify::media_player::ObjCVideo>> var0;
};

/* 340 */
struct $3CC8671D27C23BF42ADDB32F2B5E48AE
{
  signed __int64 var0;
  int var1;
  unsigned int var2;
  signed __int64 var3;
};

/* 341 */
struct Synchronizer
{
};

/* 343 */
struct SynchronizerImpl
{
  SPTSynchronizer *self;
};

/* 344 */
struct $95D729B680665BEAEFA1D6FCA8238556
{
  signed __int64 value;
  int timescale;
  unsigned int flags;
  signed __int64 epoch;
};

/* 342 */
struct SPTSynchronizer
{
  NSObject super;
  SynchronizerImpl _cpp;
  AVSampleBufferRenderSynchronizer *_avSync;
  unsigned __int64 _num_buffering;
  $95D729B680665BEAEFA1D6FCA8238556 _started_at;
};

/* 345 */
struct __compressed_pair<float **, std::allocator<float *>>
{
  float **__value_;
};

/* 346 */
struct __split_buffer<float *, std::allocator<float *>>
{
  float **__first_;
  float **__begin_;
  float **__end_;
  __compressed_pair<float **, std::allocator<float *>> __end_cap_;
};

/* 347 */
struct __compressed_pair<unsigned long, std::allocator<float>>
{
  unsigned __int64 __value_;
};

/* 348 */
struct deque<float, std::allocator<float>>
{
  __split_buffer<float *, std::allocator<float *>> __map_;
  unsigned __int64 __start_;
  __compressed_pair<unsigned long, std::allocator<float>> __size_;
};

/* 349 */
struct error_category
{
};

/* 350 */
struct error_code
{
  int var0;
  error_category *var1;
};

/* 353 */
typedef double Float64;

/* 354 */
typedef UInt32 AudioFormatID;

/* 355 */
typedef UInt32 AudioFormatFlags;

/* 352 */
struct AudioStreamBasicDescription
{
  Float64 mSampleRate;
  AudioFormatID mFormatID;
  AudioFormatFlags mFormatFlags;
  UInt32 mBytesPerPacket;
  UInt32 mFramesPerPacket;
  UInt32 mBytesPerFrame;
  UInt32 mChannelsPerFrame;
  UInt32 mBitsPerChannel;
  UInt32 mReserved;
};

/* 351 */
struct AVAssetDecompressor
{
  NSObject super;
  deque<float, std::allocator<float>> _buffer;
  AVAsset *_asset;
  AVAssetReader *_asset_reader;
  AVAssetReaderTrackOutput *_track_output;
  AudioStreamBasicDescription _audio_format;
  error_code *_error_code;
  unsigned __int64 _frames_produced_from_start;
};

/* 356 */
struct NSURLSessionWebSocketDelegate;

/* 357 */
struct NSURLSessionWebSocketDelegateWrapper
{
  NSObject super;
  NSURLSessionWebSocketDelegate *_delegate;
};

/* 358 */
struct OS_dispatch_source;

/* 359 */
struct WebSocketTaskConnectionImpl
{
  NSObject super;
  bool _isSocketConnectionClosed;
  bool _isTransportFailureSent;
  NSURLSession *_urlSession;
  NSURLSessionWebSocketTask *_webSocketTask;
  double _sendPingInterval;
  OS_dispatch_queue *_webSocketQueue;
  OS_dispatch_source *_pingTimer;
};

/* 360 */
struct TimerManager
{
  void **var0;
};

/* 361 */
struct BranchNotificationHandler
{
  NSObject super;
  void *_branch_io;
};

/* 362 */
struct BNCApplication
{
  NSObject super;
  bool _isApplication;
  bool _isApplicationExtension;
  NSString *_bundleID;
  NSString *_teamID;
  NSString *_displayName;
  NSString *_shortDisplayName;
  NSString *_displayVersionString;
  NSString *_versionString;
  NSDate *_currentBuildDate;
  NSDate *_previousAppBuildDate;
  NSDate *_firstInstallBuildDate;
  NSDate *_currentInstallDate;
  NSDate *_firstInstallDate;
  signed __int64 _updateState;
  NSString *_extensionType;
  NSString *_branchExtensionType;
  NSString *_defaultURLScheme;
  NSString *_applicationID;
  NSString *_pushNotificationEnvironment;
  NSArray *_keychainAccessGroups;
  NSArray *_associatedDomains;
};

/* 363 */
struct BNCDevice
{
  NSObject super;
  NSString *_vendorID;
  bool _isSimulator;
  bool _adTrackingIsEnabled;
  NSString *_hardwareIDType;
  NSString *_brandName;
  NSString *_modelName;
  NSString *_systemName;
  NSString *_systemVersion;
  NSString *_systemBuildVersion;
  double _screenDPI;
  NSString *_advertisingID;
  NSString *_netAddress;
  NSString *_country;
  NSString *_language;
  NSString *_userAgent;
  CGSize _screenSize;
};

/* 364 */
struct BNCEncoder
{
  NSObject super;
};

/* 365 */
struct BNCKeyChain
{
  NSObject super;
  NSString *_securityAccessGroup;
};

/* 366 */
struct BNCLocalization
{
  NSObject super;
  NSString *_currentLanguage;
  NSDictionary *_currentLanguageDictionary;
};

/* 367 */
struct BNCNetworkServiceProtocol;

/* 368 */
struct BranchConfiguration
{
  NSObject super;
  NSString *_key;
  NSString *_branchAPIServiceURL;
  Class _networkServiceClass;
  NSArray *_blackListURLRegex;
  BNCSettings *_settings;
};

/* 369 */
struct BNCSettings
{
  NSObject super;
  OS_dispatch_queue *_saveQueue;
  OS_dispatch_source *_saveTimer;
  BNCSettingsProxy *_proxy;
  BranchMutableDictionary *_requestMetadataDictionary;
  BranchMutableDictionary *_instrumentationDictionary;
  bool _limitFacebookTracking;
  bool _userTrackingDisabled;
  id _settingsSavedBlock;
  NSString *_randomizedDeviceToken;
  NSString *_randomizedBundleToken;
  NSString *_deviceFingerprintID;
  NSString *_identityID;
  NSString *_userIdentityForDeveloper;
  NSString *_sessionID;
  NSString *_linkCreationURL;
  signed __int64 _URLBlackListVersion;
  NSDate *_URLBlackListLastRefreshDate;
  NSArray *_URLBlackList;
  BNCPersistence *_persistence;
};

/* 381 */
struct NSProxy
{
  Class isa;
};

/* 380 */
struct BNCSettingsProxy
{
  NSProxy super;
  BNCSettings *_settings;
};

/* 382 */
struct BranchMutableDictionary
{
  NSMutableDictionary super;
  NSMutableDictionary *_dictionary;
};

/* 370 */
struct BNCPersistence
{
  NSObject super;
  NSString *_appGroup;
};

/* 371 */
struct BNCNetworkAPIService
{
  NSObject super;
  BNCNetworkServiceProtocol *_networkService;
  BranchConfiguration *_configuration;
  BNCSettings *_settings;
  NSOperationQueue *_operationQueue;
  NSMutableDictionary *_archivedOperations;
  BNCPersistence *_persistence;
};

/* 372 */
struct BNCNetworkOperationProtocol;

/* 373 */
struct BranchSession
{
  NSObject super;
  bool _isFirstSession;
  bool _isBranchURL;
  bool _matchGuaranteed;
  NSString *_sessionID;
  NSDate *_clickTimestamp;
  NSURL *_referringURL;
  NSString *_deviceFingerprintID;
  NSString *_randomizedDeviceToken;
  NSString *_identityID;
  NSString *_randomizedBundleToken;
  NSString *_userIdentityForDeveloper;
  NSString *_linkCreationURL;
  BranchUniversalObject *_linkContent;
  BranchLinkProperties *_linkProperties;
  NSDictionary *_data;
};

/* 390 */
struct BranchUniversalObject
{
  NSObject super;
  bool _locallyIndex;
  bool _publiclyIndex;
  NSString *_canonicalIdentifier;
  NSString *_canonicalUrl;
  NSString *_title;
  NSString *_contentDescription;
  NSString *_imageUrl;
  NSArray *_keywords;
  NSDate *_creationDate;
  NSDate *_expirationDate;
  BranchContentMetadata *_contentMetadata;
};

/* 386 */
struct BranchLinkProperties
{
  NSObject super;
  NSArray *_tags;
  NSString *_feature;
  NSString *_alias;
  NSString *_channel;
  NSString *_stage;
  NSString *_campaign;
  signed __int64 _matchDuration;
  signed __int64 _linkType;
  NSMutableDictionary *_controlParams;
};

/* 391 */
struct BranchContentMetadata
{
  NSObject super;
  NSMutableArray *_imageCaptions;
  NSMutableDictionary *_customMetadata;
  NSString *_contentSchema;
  double _quantity;
  NSDecimalNumber *_price;
  NSString *_currency;
  NSString *_sku;
  NSString *_productName;
  NSString *_productBrand;
  NSString *_productCategory;
  NSString *_productVariant;
  NSString *_condition;
  double _ratingAverage;
  signed __int64 _ratingCount;
  double _ratingMax;
  double _rating;
  NSString *_addressStreet;
  NSString *_addressCity;
  NSString *_addressRegion;
  NSString *_addressCountry;
  NSString *_addressPostalCode;
  double _latitude;
  double _longitude;
};

/* 375 */
struct NSOperation
{
  NSObject super;
};

/* 374 */
struct BNCNetworkAPIOperation
{
  NSOperation super;
  BNCNetworkOperationProtocol *_operation;
  NSDate *_startDate;
  NSDate *_timeoutDate;
  NSError *_error;
  BranchSession *_session;
  BNCNetworkServiceProtocol *_networkService;
  BNCSettings *_settings;
  NSURL *_URL;
  NSMutableDictionary *_dictionary;
  NSString *_identifier;
  id _completion;
};

/* 376 */
struct BNCNetworkInformation
{
  NSObject super;
  NSString *_interface;
  NSData *_address;
  NSString *_displayAddress;
  NSData *_inetAddress;
  NSString *_displayInetAddress;
  signed __int64 _inetAddressType;
};

/* 377 */
struct BNCNetworkService
{
  NSObject super;
  NSOperationQueue *_serviceQueue;
  NSURLSession *_session;
};

/* 378 */
struct BNCNetworkOperation
{
  NSObject super;
  NSMutableURLRequest *_request;
  NSError *_error;
  NSData *_responseData;
  signed __int64 _sessionState;
  BNCNetworkService *_networkService;
  NSHTTPURLResponse *_response;
  NSURLSessionTask *_sessionTask;
  id _completionBlock;
};

/* 379 */
struct BNCQRCodeCache
{
  NSObject super;
  NSMutableDictionary *_cache;
};

/* 383 */
struct BNCURLBlackList
{
  NSObject super;
  NSArray *_blackList;
  bool _hasRefreshedBlackListFromServer;
  signed __int64 _blackListVersion;
  NSArray *_blackListRegex;
  BNCNetworkServiceProtocol *_networkService;
  NSError *_error;
  NSURL *_blackListJSONURL;
};

/* 384 */
struct BNCUserAgentCollector
{
  NSObject super;
  NSString *_userAgent;
  WKWebView *_webview;
};

/* 385 */
struct BranchEvent
{
  NSObject super;
  NSMutableDictionary *_customData;
  NSMutableArray *_contentItems;
  NSString *_eventName;
  NSString *_transactionID;
  NSString *_currency;
  NSDecimalNumber *_revenue;
  NSDecimalNumber *_shipping;
  NSDecimalNumber *_tax;
  NSString *_coupon;
  NSString *_affiliation;
  NSString *_eventDescription;
  NSString *_searchQuery;
  signed __int64 _adType;
};

/* 388 */
struct BranchDelegate;

/* 387 */
struct Branch
{
  NSObject super;
  BranchDelegate *_delegate;
  id _sessionStartedBlock;
  BNCNetworkAPIService *_networkAPIService;
  BranchConfiguration *_configuration;
  BNCSettings *_settings;
  BNCURLBlackList *_URLBlackList;
  BNCURLBlackList *_userURLBlackList;
  NSURL *_delayedOpenURL;
  OS_dispatch_source *_delayedOpenTimer;
  OS_dispatch_queue *_workQueue;
  signed __int64 _sessionState;
};

/* 389 */
struct BranchQRCode
{
  NSObject super;
  NSColor *_codeColor;
  NSColor *_backgroundColor;
  NSString *_centerLogo;
  NSNumber *_width;
  NSNumber *_margin;
  signed __int64 _imageFormat;
};

/* 392 */
struct Reachability
{
  NSObject super;
  bool _localWiFiRef;
  __SCNetworkReachability *_reachabilityRef;
};

/* 393 */
struct ReachabilityChangedListener
{
  NSObject super;
  void *_network_notifier;
};

